from nltk import data
import spacy

skill_patterns = [

    # ── HR & Management ───────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "fmla"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "osha"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "strategic"}, {"LOWER": "planning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "workers"}, {"LOWER": "compensation"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "leadership"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "employee"}, {"LOWER": "relations"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "labor"}, {"LOWER": "union"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "executive"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "talent"}, {"LOWER": "acquisition"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "performance"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "succession"}, {"LOWER": "planning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "change"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "conflict"}, {"LOWER": "resolution"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "onboarding"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "payroll"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "benefits"}, {"LOWER": "administration"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "workforce"}, {"LOWER": "planning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "diversity"}, {"LOWER": "inclusion"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "coaching"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mentoring"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "team"}, {"LOWER": "building"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cross"}, {"LOWER": "functional"}, {"LOWER": "collaboration"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "stakeholder"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "project"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pmp"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "scrum"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "agile"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "kanban"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "lean"}, {"LOWER": "six"}, {"LOWER": "sigma"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "six"}, {"LOWER": "sigma"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "waterfall"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "jira"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "confluence"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "trello"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "asana"}]},

    # ── Programming Languages ─────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "python"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "java"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "javascript"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "typescript"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "c++"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "c#"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "golang"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "go"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "rust"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ruby"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "php"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "swift"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "kotlin"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "scala"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "r"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "matlab"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bash"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "shell"}, {"LOWER": "scripting"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "perl"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "vba"}]},

    # ── Web & Frontend ────────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "html"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "css"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "react"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "react.js"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "angular"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "vue"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "vue.js"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "next.js"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "node.js"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "express.js"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "tailwind"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bootstrap"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sass"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "graphql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "rest"}, {"LOWER": "api"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "restful"}, {"LOWER": "api"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mern"}, {"LOWER": "stack"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mean"}, {"LOWER": "stack"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "webpack"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "redux"}]},

    # ── Backend & Frameworks ──────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "django"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "flask"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "fastapi"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "spring"}, {"LOWER": "boot"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "spring"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "rails"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ruby"}, {"LOWER": "on"}, {"LOWER": "rails"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "laravel"}]},
    {"label": "SKILL", "pattern": [{"LOWER": ".net"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "asp.net"}]},

    # ── Databases ─────────────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "sql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mysql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "postgresql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sqlite"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mongodb"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "redis"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cassandra"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "dynamodb"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "elasticsearch"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "oracle"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sql"}, {"LOWER": "server"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "database"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "nosql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "neo4j"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "firebase"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "supabase"}]},

    # ── Cloud & DevOps ────────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "aws"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "azure"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "gcp"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "google"}, {"LOWER": "cloud"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "docker"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "kubernetes"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "terraform"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ansible"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "jenkins"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ci/cd"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ci"}, {"LOWER": "cd"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "github"}, {"LOWER": "actions"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "gitlab"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "linux"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "unix"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "nginx"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "apache"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "microservices"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "serverless"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cloudformation"}]},

    # ── Machine Learning / AI ─────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "machine"}, {"LOWER": "learning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "deep"}, {"LOWER": "learning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "nlp"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "natural"}, {"LOWER": "language"}, {"LOWER": "processing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "computer"}, {"LOWER": "vision"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "tensorflow"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pytorch"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "keras"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "scikit"}, {"LOWER": "learn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sklearn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "xgboost"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "lightgbm"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "catboost"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "spacy"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hugging"}, {"LOWER": "face"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "transformers"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bert"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "gpt"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "llm"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "generative"}, {"LOWER": "ai"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "langchain"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "rag"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "retrieval"}, {"LOWER": "augmented"}, {"LOWER": "generation"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "reinforcement"}, {"LOWER": "learning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "random"}, {"LOWER": "forest"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "neural"}, {"LOWER": "network"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cnn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "rnn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "lstm"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "tf"}, {"LOWER": "idf"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "word2vec"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "feature"}, {"LOWER": "engineering"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "model"}, {"LOWER": "deployment"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mlops"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mlflow"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hyperparameter"}, {"LOWER": "tuning"}]},

    # ── Data Science & Analytics ──────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "data"}, {"LOWER": "science"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "data"}, {"LOWER": "analysis"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "data"}, {"LOWER": "visualization"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "data"}, {"LOWER": "engineering"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "data"}, {"LOWER": "pipeline"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "etl"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pandas"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "numpy"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "matplotlib"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "seaborn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "plotly"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "tableau"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "power"}, {"LOWER": "bi"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "looker"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hadoop"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "spark"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "apache"}, {"LOWER": "spark"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "kafka"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "airflow"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "dbt"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "snowflake"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bigquery"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "statistical"}, {"LOWER": "analysis"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "a/b"}, {"LOWER": "testing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hypothesis"}, {"LOWER": "testing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "regression"}, {"LOWER": "analysis"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "time"}, {"LOWER": "series"}]},

    # ── Cybersecurity ─────────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "cybersecurity"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "network"}, {"LOWER": "security"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "penetration"}, {"LOWER": "testing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ethical"}, {"LOWER": "hacking"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "siem"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "firewall"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "vulnerability"}, {"LOWER": "assessment"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "iam"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "soc"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "incident"}, {"LOWER": "response"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "gdpr"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "iso"}, {"LOWER": "27001"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "nist"}]},

    # ── Office & Productivity ─────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "excel"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "excel"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "office"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ms"}, {"LOWER": "word"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "word"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "powerpoint"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "outlook"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "access"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sharepoint"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "google"}, {"LOWER": "sheets"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "google"}, {"LOWER": "workspace"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "google"}, {"LOWER": "docs"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "database"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "quattro"}, {"LOWER": "pro"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "quark"}, {"LOWER": "express"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "harvard"}, {"LOWER": "graphics"}]},

    # ── Finance & Accounting ──────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "financial"}, {"LOWER": "analysis"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "financial"}, {"LOWER": "modeling"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "accounting"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bookkeeping"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "budgeting"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "forecasting"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "gaap"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ifrs"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "quickbooks"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sap"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "oracle"}, {"LOWER": "financials"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "risk"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "valuation"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "equity"}, {"LOWER": "research"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "portfolio"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "tax"}, {"LOWER": "compliance"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "audit"}]},

    # ── Marketing & Sales ─────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "seo"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sem"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "google"}, {"LOWER": "analytics"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "content"}, {"LOWER": "marketing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "social"}, {"LOWER": "media"}, {"LOWER": "marketing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "email"}, {"LOWER": "marketing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "crm"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "salesforce"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hubspot"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "digital"}, {"LOWER": "marketing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "brand"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "market"}, {"LOWER": "research"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "lead"}, {"LOWER": "generation"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "b2b"}, {"LOWER": "sales"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "b2c"}, {"LOWER": "sales"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "product"}, {"LOWER": "marketing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "growth"}, {"LOWER": "hacking"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "google"}, {"LOWER": "ads"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "facebook"}, {"LOWER": "ads"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "copywriting"}]},

    # ── Healthcare & Medical ──────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "clinical"}, {"LOWER": "research"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ehr"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "emr"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hipaa"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "icd"}, {"LOWER": "10"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "patient"}, {"LOWER": "care"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cpr"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "medical"}, {"LOWER": "coding"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "phlebotomy"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "nursing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pharmacology"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "telemedicine"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "fda"}, {"LOWER": "regulations"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "clinical"}, {"LOWER": "trials"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bioinformatics"}]},

    # ── Engineering & Manufacturing ───────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "autocad"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "solidworks"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cad"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cam"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "finite"}, {"LOWER": "element"}, {"LOWER": "analysis"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "fea"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "plc"}, {"LOWER": "programming"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "quality"}, {"LOWER": "control"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "iso"}, {"LOWER": "9001"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "supply"}, {"LOWER": "chain"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "supply"}, {"LOWER": "chain"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "inventory"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "erp"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "manufacturing"}, {"LOWER": "operations"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "process"}, {"LOWER": "improvement"}]},

    # ── Design & Creative ─────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "photoshop"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "illustrator"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "indesign"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "figma"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sketch"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "adobe"}, {"LOWER": "xd"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ui"}, {"LOWER": "ux"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ux"}, {"LOWER": "design"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "ui"}, {"LOWER": "design"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "user"}, {"LOWER": "research"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "wireframing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "prototyping"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "motion"}, {"LOWER": "graphics"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "after"}, {"LOWER": "effects"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "premiere"}, {"LOWER": "pro"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "blender"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "3d"}, {"LOWER": "modeling"}]},

    # ── Testing & QA ─────────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "selenium"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cypress"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "jest"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pytest"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "unit"}, {"LOWER": "testing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "integration"}, {"LOWER": "testing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "test"}, {"LOWER": "automation"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "quality"}, {"LOWER": "assurance"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "qa"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "postman"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "load"}, {"LOWER": "testing"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "performance"}, {"LOWER": "testing"}]},

    # ── Version Control & Collaboration ──────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "git"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "github"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bitbucket"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "svn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "code"}, {"LOWER": "review"}]},

    # ── Soft Skills ───────────────────────────────────────────────────────────
    {"label": "SKILL", "pattern": [{"LOWER": "communication"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "problem"}, {"LOWER": "solving"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "critical"}, {"LOWER": "thinking"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "time"}, {"LOWER": "management"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "attention"}, {"LOWER": "to"}, {"LOWER": "detail"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "presentation"}, {"LOWER": "skills"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "analytical"}, {"LOWER": "skills"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "decision"}, {"LOWER": "making"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "negotiation"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "multitasking"}]},

    # These are currently missing and will cause misses on most ML/AI resumes
    {"label": "SKILL", "pattern": [{"LOWER": "tensorflow"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "keras"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pytorch"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "bert"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "huggingface"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "transformers"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "fastapi"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "opencv"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mediapipe"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "lstm"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "cnn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "docker"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "aws"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "git"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "react"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "node"}, {"LOWER": "js"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "rest"}, {"LOWER": "api"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "postgresql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mongodb"}]},

    # Aliases — same skill, different surface forms
    {"label": "SKILL", "pattern": [{"LOWER": "huggingface"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "hugging"}, {"LOWER": "face"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "machine"}, {"LOWER": "learning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "deep"}, {"LOWER": "learning"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "scikit"}, {"LOWER": "learn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sklearn"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "transformers"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "pytorch"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "torch"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "docker"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "aws"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "gcp"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "sql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "mysql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "postgresql"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "kubernetes"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "streamlit"}]},
    {"label": "SKILL", "pattern": [{"LOWER": "scikit"}]},
]

SKILL_ALIASES = {
    "Huggingface":     "Hugging Face",
    "Hf":              "Hugging Face",
    "Sklearn":         "Scikit-Learn",
    "Scikit Learn":    "Scikit-Learn",
    "Scikit-Learn":    "Scikit-Learn",
    "Torch":           "Pytorch",
    "Ml":              "Machine Learning",
    "Dl":              "Deep Learning",
    "Cv":              "Computer Vision",
    "Nlp":             "Nlp",
    "Mysql":           "Sql",
    "Postgresql":      "Sql",
    "Mariadb":         "Sql",
    "Github":          "Git",
    "Rest Api":        "Rest Api",
    "Restful Api":     "Rest Api",
    "Fastapi":         "Fastapi",
    "Fast Api":        "Fastapi",
    "Aws":             "Aws",
    "Amazon Web Services": "Aws",
    "Gcp":             "Gcp",
    "Google Cloud":    "Gcp",
}

def normalize_skill(skill: str) -> str:
    titled = skill.strip().title()
    return SKILL_ALIASES.get(titled, titled)

class SkillExtractor:
    def __init__(self):
        self.nlp = spacy.load("en_core_web_sm")
        ruler = self.nlp.add_pipe("entity_ruler", before="ner")
        ruler.add_patterns(skill_patterns)

        
    def extract(self, text: str):
        doc = self.nlp(text)
        data = {"SKILLS": set(), "ORGANIZATIONS": set(),
                "EDUCATION_CERT": set(), "EXPERIENCE_PERIODS": set()}
        for ent in doc.ents:
            if len(ent.text.strip()) < 2:
                continue
            
            if ent.label_ == "SKILL":
                normalized = normalize_skill(ent.text)
                data["SKILLS"].add(normalized)
            elif ent.label_ in ["ORG", "NORP"]:
                data["ORGANIZATIONS"].add(ent.text)
            elif ent.label_ in ["DATE", "QUANTITY"] and any(c.isdigit() for c in ent.text):
                data["EXPERIENCE_PERIODS"].add(ent.text)
            elif any(k in ent.text for k in ["Degree", "Bachelor", "Master"]):
                data["EDUCATION_CERT"].add(ent.text)
        
        return data